export const rootCategories = [
  "Tradicional",
  "Americano",
  "Cremoso",
  "Gelado",
  "Com leite",
  "Alcoólico",
  "Especial",
  "Brasileira",
  "Árabe",
  "Doces & Bolos",
  "Lanches",
  "Saudável",
  "Japonesa",
  "Carnes",
  "Pizza",
  "Italiana",
  "Vegetariana",
];

export const coffeeDeliveryBenefits = [
  {
    icon: "/icons/shopping-cart.svg",
    benefit: "Compra simples e segura",
    iconBg: "brand-yellow-dark",
  },
  {
    icon: "/icons/box.svg",
    benefit: "Embalagem segura e sustentável",
    iconBg: "base-text",
  },
  {
    icon: "/icons/clock.svg",
    benefit: "Entrega rápida e rastreada",
    iconBg: "brand-yellow",
  },
  {
    icon: "/icons/coffee-cup.svg",
    benefit: "Café fresquinho toda hora",
    iconBg: "brand-purple",
  },
];

export const coffeesList = [
  {
    id: 1,
    type: "coffee",
    tags: ["tradicional"],
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    photo: "tradicional.png",
    price: 7.9,
  },
  {
    id: 2,
    type: "coffee",
    tags: ["tradicional"],
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    photo: "americano.png",
    price: 7.9,
  },
  {
    id: 3,
    type: "coffee",
    tags: ["tradicional"],
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    photo: "cremoso.png",
    price: 8.5,
  },
  {
    id: 4,
    type: "coffee",
    tags: ["tradicional", "gelado"],
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    photo: "gelado.png",
    price: 8.9,
  },
  {
    id: 5,
    type: "coffee",
    tags: ["tradicional", "com leite"],
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    photo: "leite.png",
    price: 11.9,
  },
  {
    id: 6,
    type: "coffee",
    tags: ["tradicional", "com leite"],
    name: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    photo: "latte.png",
    price: 14.9,
  },
  {
    id: 7,
    type: "coffee",
    tags: ["tradicional", "com leite"],
    name: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    photo: "capuccino.png",
    price: 11.9,
  },
  {
    id: 8,
    type: "coffee",
    tags: ["tradicional", "com leite"],
    name: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    photo: "macchiato.png",
    price: 8.5,
  },
  {
    id: 9,
    type: "coffee",
    tags: ["tradicional", "com leite"],
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    photo: "mocaccino.png",
    price: 14.5,
  },
  {
    id: 10,
    type: "coffee",
    tags: ["especial", "com leite"],
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    photo: "chocolate.png",
    price: 15.9,
  },
  {
    id: 11,
    type: "coffee",
    tags: ["especial", "alcoólico", "gelado"],
    name: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    photo: "cubano.png",
    price: 16.9,
  },
  {
    id: 12,
    type: "coffee",
    tags: ["especial"],
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    photo: "havaiano.png",
    price: 15.9,
  },
  {
    id: 13,
    type: "coffee",
    tags: ["especial"],
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    photo: "arabe.png",
    price: 15.9,
  },
  {
    id: 14,
    type: "coffee",
    tags: ["especial", "alcoólico"],
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    photo: "irlandes.png",
    price: 15.9,
  },
];

export const flashFood = [
  {
    image: "/assets/food/flash-deal-1.png",
    name: "Salada de Quinoa e Abacate",
    restaurant: "Fogo de Chão",
    remainingDays: 2,
  },
  {
    image: "/assets/food/flash-deal-2.png",
    name: "Farfalle ao Pesto com Tomatinhos Cereja",
    restaurant: "Olive Garden",
    remainingDays: 5,
  },
  {
    image: "/assets/food/flash-deal-3.png",
    name: "Bowl Vegano com Grão-de-bico e Abacate",
    restaurant: "Coco Bambu",
    remainingDays: 7,
  },
  {
    image: "/assets/food/flash-deal-4.png",
    name: "Curry de Vegetais com Leite de Coco",
    restaurant: "Omatuto",
    remainingDays: 12,
  },
];

export const howItWorks = [
  {
    title: "Informe o endereço",
    description:
      "Defina o endereço de entrega para qual seu pedido será entregue.",
    image: "/assets/food/how-it-works-1.svg",
  },
  {
    title: "Escolha seu pedido",
    description: "Viage por uma variedade de opções e vá na sua favorita.",
    image: "/assets/food/how-it-works-2.svg",
  },
  {
    title: "Pagamento facilitado",
    description:
      "É rápido, seguro e simples. Escolha dentre diferentes formas de pagamento.",
    image: "/assets/food/how-it-works-3.svg",
  },
  {
    title: "Aproveite seu pedido",
    description:
      "A comida é preparada por um de nossos restaurantes parceiros e entregue na porta de sua casa.",
    image: "/assets/food/how-it-works-4.svg",
  },
];

export const foodList = [
  {
    id: 1,
    type: "food",
    tags: ["Hamburguer"],
    name: "Cheese Burguer",
    description: "Pão macio, carne grelhada e queijo derretido.",
    photo: "cheese-burguer.png",
    price: 12.9,
  },
  {
    id: 2,
    type: "food",
    tags: ["Hamburguer"],
    name: "X-Bacon",
    description: "Pão macio, carne suculenta, queijo derretido e muito bacon crocante.",
    photo: "cheese-bacon.png",
    price: 14.9,
  },
  {
    id: 3,
    type: "food",
    tags: ["Hamburguer"],
    name: "Chicken Burger",
    description: "Peito de frango grelhado, com molho especial, alface e pão macio.",
    photo: "chicken-burger.png",
    price: 13.9,
  },
  {
    id: 4,
    type: "food",
    tags: ["Hamburguer"],
    name: "Big Cheese",
    description: "Três suculentas carnes, muito queijo derretido e um molho especial.",
    photo: "big-cheese.png",
    price: 16.9,
  },
  {
    id: 5,
    type: "food",
    tags: ["Pizza"],
    name: "Pizza de Mussarela",
    description: "Massa fina, molho de tomate e queijo derretido.",
    photo: "pizza-mozarella.png",
    price: 63.9,
  },
  {
    id: 6,
    type: "food",
    tags: ["Pizza"],
    name: "Pizza de Frango",
    description: "Massa crocante, molho de tomate e frango desfiado.",
    photo: "pizza-chicken.png",
    price: 69.9,
  },
  {
    id: 7,
    type: "food",
    tags: ["Pizza"],
    name: "Pizza de Pepperoni",
    description: "Base crocante e generosas fatias de pepperoni levemente picantes, douradas no forno.",
    photo: "pizza-pepperoni.png",
    price: 69.9,
  },
  {
    id: 8,
    type: "food",
    tags: ["Pizza"],
    name: "Pizza de Chocolate",
    description: "Uma delícia doce e irresistível!",
    photo: "pizza-chocolate.png",
    price: 74.9,
  },
  {
    id: 9,
    type: "food",
    tags: ["Japa"],
    name: "Combo de Sushi",
    description: "Combo com os melhores tipos de sushi!",
    photo: "japanese-combo.png",
    price: 47.9,
  },
  {
    id: 10,
    type: "food",
    tags: ["Japa"],
    name: "Temaki",
    description: "Salmão irresistível envolto por algas secas!",
    photo: "japanese-temaki.png",
    price: 15.9,
  },
  {
    id: 11,
    type: "food",
    tags: ["Japa"],
    name: "Shimeji",
    description: "O prato fungi mais adorado da cultura japonesa!",
    photo: "japanese-shimeji.png",
    price: 21.9,
  },
  {
    id: 12,
    type: "food",
    tags: ["Japa"],
    name: "Porção de Hot Roll",
    description: "Uma porção de hot rolls com cream-cheese!",
    photo: "japanese-hotroll.png",
    price: 15.9,
  },
  {
    id: 13,
    type: "food",
    tags: ["vegano"],
    name: "Hambúrguer Vegano",
    description: "Que tal uma opção de hambúrguer vegano?",
    photo: "veggie-burger.png",
    price: 17.9,
  },
  {
    id: 14,
    type: "food",
    tags: ["vegano"],
    name: "Sushi Vegano",
    description: "Uma opção de sushi vegano para você!",
    photo: "veggie-sushi.png",
    price: 24.9,
  },
  {
    id: 15,
    type: "food",
    tags: ["vegano"],
    name: "Pizza Vegana",
    description: "Uma pizza vegana deliciosa!",
    photo: "veggie-pizza.png",
    price: 29.9,
  },
  {
    id: 16,
    type: "food",
    tags: ["vegano"],
    name: "Bolo Vegano",
    description: "Um bolo vegano de baunilha com cobertura.",
    photo: "veggie-vanillac.png",
    price: 37.9,
  },

];

export const deliveryDetails = [
  {
    title: "Fome de",
    highlight: "sanduíches/lanches?",
    description:
      "Desfrute de sanduíches grandes e perfeitos. A combinação ideal de sabor e crocância em cada mordida.",
    buttonText: "Peça agora",
    image: "/assets/food/details-image-1.png",
    reverse: false,
  },
  {
    title: "Frango frito",
    highlight: "no almoço de domingo?",
    description:
      "Experimente o melhor frango frito, mergulhado em um saboroso molho de limão e pimenta.",
    buttonText: "Peça agora",
    image: "/assets/food/details-image-2.png",
    reverse: true,
  },
  {
    title: "Que tal uma",
    highlight: "pizza?",
    description:
      "Junte-se a um amigo e saboreie uma pizza deliciosa. Aproveite as melhores ofertas e não perca essa delícia.",
    buttonText: "Peça agora",
    image: "/assets/food/details-image-3.png",
    reverse: false,
  },
];
